/*
 * Pipeline API
 *
 * Pipeline is a feature rich application platform, built for containers on top of Kubernetes to automate the DevOps experience, continuous application development and the lifecycle of deployments. 
 *
 * API version: latest
 * Contact: info@banzaicloud.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pipeline

// NodePoolAutoScalingPatch - Node pool auto scaling settings patch.
type NodePoolAutoScalingPatch struct {

	// Enable node pool autoscaling.
	Enabled bool `json:"enabled,omitempty"`

	// Minimum node pool size.
	MinSize int32 `json:"minSize,omitempty"`

	// Maximum node pool size.
	MaxSize int32 `json:"maxSize,omitempty"`
}
