// Code generated by mockery v1.0.0. DO NOT EDIT.

package process

import (
	context "context"

	auth "github.com/banzaicloud/pipeline/src/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// GetProcess provides a mock function with given fields: ctx, org, id
func (_m *MockService) GetProcess(ctx context.Context, org auth.Organization, id string) (Process, error) {
	ret := _m.Called(ctx, org, id)

	var r0 Process
	if rf, ok := ret.Get(0).(func(context.Context, auth.Organization, string) Process); ok {
		r0 = rf(ctx, org, id)
	} else {
		r0 = ret.Get(0).(Process)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, auth.Organization, string) error); ok {
		r1 = rf(ctx, org, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProcesses provides a mock function with given fields: ctx, query
func (_m *MockService) ListProcesses(ctx context.Context, query Process) ([]Process, error) {
	ret := _m.Called(ctx, query)

	var r0 []Process
	if rf, ok := ret.Get(0).(func(context.Context, Process) []Process); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Process)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, Process) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogProcess provides a mock function with given fields: ctx, proc
func (_m *MockService) LogProcess(ctx context.Context, proc Process) (Process, error) {
	ret := _m.Called(ctx, proc)

	var r0 Process
	if rf, ok := ret.Get(0).(func(context.Context, Process) Process); ok {
		r0 = rf(ctx, proc)
	} else {
		r0 = ret.Get(0).(Process)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, Process) error); ok {
		r1 = rf(ctx, proc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogProcessEvent provides a mock function with given fields: ctx, proc
func (_m *MockService) LogProcessEvent(ctx context.Context, proc ProcessEvent) (ProcessEvent, error) {
	ret := _m.Called(ctx, proc)

	var r0 ProcessEvent
	if rf, ok := ret.Get(0).(func(context.Context, ProcessEvent) ProcessEvent); ok {
		r0 = rf(ctx, proc)
	} else {
		r0 = ret.Get(0).(ProcessEvent)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ProcessEvent) error); ok {
		r1 = rf(ctx, proc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
